/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Login_Form extends javax.swing.JFrame implements Login_Interface {

    /**
     * Creates new form Login_Form
     */
    public void openLogin() {
        System.out.println("Open Login");
    }

    private String massage;
    Login aa = new Login();

    public Login_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        setBackground(new java.awt.Color(95, 147, 64));
        setLocation(new java.awt.Point(10, 3));
        setResizable(false);

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        login.setForeground(new java.awt.Color(95, 145, 64));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });

        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Signin to CryptoExchange Wallet");

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Image/Login.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        register.setForeground(new java.awt.Color(95, 145, 64));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(email)
                                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(register, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(8, 8, 8)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void resetText() {
        email.setText("");
        password.setText("");
    }

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
            email.requestFocus();
        } else if (password.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
            password.requestFocus();
        } else {
            aa.setEmail(email.getText());
            aa.setPassword(password.getText());
            Session.setUserID(email.getText());
            massage = aa.loginCheck(aa.getEmail(), aa.getPassword());
            if (Session.getLoginStatus() == "Active") {
                dispose();
                Menu form = new Menu();
                form.getContentPane().setBackground(Color.decode("#5f9140"));
                form.openMenu();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (email.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
                email.requestFocus();
            } else if (password.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
                password.requestFocus();
            } else {
                aa.setEmail(email.getText());
                aa.setPassword(password.getText());
                Session.setUserID(email.getText());
                massage = aa.loginCheck(aa.getEmail(), aa.getPassword());
                if (Session.getLoginStatus() == "Active") {
                    dispose();
                    Menu form = new Menu();
                    form.getContentPane().setBackground(Color.decode("#5f9140"));
                    form.openMenu();
                    form.setLocationRelativeTo(null);
                    form.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
                }
            }
        }
    }//GEN-LAST:event_loginKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (email.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
                email.requestFocus();
            } else if (password.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
                password.requestFocus();
            } else {
                aa.setEmail(email.getText());
                aa.setPassword(password.getText());
                Session.setUserID(email.getText());
                massage = aa.loginCheck(aa.getEmail(), aa.getPassword());
                if (Session.getLoginStatus() == "Active") {
                    dispose();
                    Menu form = new Menu();
                    form.getContentPane().setBackground(Color.decode("#5f9140"));
                    form.openMenu();
                    form.setLocationRelativeTo(null);
                    form.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
                }
            }
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (email.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
                email.requestFocus();
            } else if (password.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
                password.requestFocus();
            } else {
                aa.setEmail(email.getText());
                aa.setPassword(password.getText());
                Session.setUserID(email.getText());
                massage = aa.loginCheck(aa.getEmail(), aa.getPassword());
                if (Session.getLoginStatus() == "Active") {
                    dispose();
                    Menu.preview();
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
                }
            }
        }
    }//GEN-LAST:event_emailKeyPressed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        dispose();
        Register_Form.preview();
    }//GEN-LAST:event_registerActionPerformed

    private void registerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerKeyPressed
        dispose();
        Register_Form.preview();
    }//GEN-LAST:event_registerKeyPressed

    public static void preview() {
        Login_Form form = new Login_Form();
        form.getContentPane().setBackground(Color.decode("#5f9140"));
        form.openLogin();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            preview();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton login;
    private javax.swing.JTextField password;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
